# Generated by Django 2.2.5 on 2019-09-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20, verbose_name='书名')),
                ('bpub_date', models.DateField(verbose_name='发布日期')),
                ('bread', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('bcomment', models.PositiveIntegerField(default=0, verbose_name='评论量')),
                ('isDelete', models.BooleanField(db_column='is_delete', default=False, verbose_name='逻辑删除')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'book_info',
            },
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20, verbose_name='人物姓名')),
                ('pgender', models.BooleanField(default=True, verbose_name='人物性别')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('pcomment', models.CharField(max_length=200, null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '人物信息',
                'verbose_name_plural': '人物信息',
                'db_table': 'person_info',
            },
        ),
    ]
